[DDCE-2637] SBT Upgrade
hmrc/bank-holidays pull request #13
Opened 2022-08-18 12:21 UTC by Nboaram

2022-08-24 09:54 UTC, frikit requested changes
1) Please add scalafmt plugin + conf file, you can see example here https://github.com/hmrc/national-insurance-performance-tests/pull/14 , make sure you include and run scalafmt task in run_all_tests.sh
2) Update run_all_tests.sh and add dependencyUpdates
3) once you finish step 2 now you can see:
`[info] Found 11 dependency updates for bank-holidays
[info]   com.github.tomakehurst:wiremock-jre8      : 2.27.2              -> 2.33.2         
[info]   com.typesafe.play:play-test               : 2.8.15  -> 2.8.16                     
[info]   com.vladsch.flexmark:flexmark-all         : 0.35.10             -> 0.64.0         
[info]   org.jsoup:jsoup                           : 1.14.2  -> 1.14.3   -> 1.15.3         
[info]   org.mockito:mockito-core                  : 3.12.4                        -> 4.7.0
[info]   org.scala-lang:scala-library              : 2.12.16             -> 2.13.8         
[info]   org.scalacheck:scalacheck                 : 1.15.4              -> 1.16.0         
[info]   org.scalatest:scalatest                   : 3.0.9               -> 3.2.13         
[info]   org.scalatestplus.play:scalatestplus-play : 4.0.3                         -> 5.1.0
[info]   org.scalatestplus:mockito-3-4             : 3.2.9.0 -> 3.2.10.0                   
[info]   uk.gov.hmrc:bootstrap-backend-play-28     : 7.0.0               -> 7.1.0  `
Please check and update most of these but keep boostrap backend 6.4, if it is confusing check other PRs for more info

2022-08-24 09:54 UTC, frikit commented on build.sbt
> -    scalacOptions += "-P:silencer:pathFilters=target/.*",
why have you deleted silencer rules? Now when you can compile you see 14 warnings for routes files which should be hidden with this plugin

2022-08-24 09:54 UTC, frikit commented on build.sbt
> -    scalacOptions += "-P:silencer:globalFilters=possible missing interpolator: detected interpolated identifier `\\$date`",
there is no mongo repo inside this can be deleted I guess

2022-08-24 09:54 UTC, frikit commented on build.sbt
> -    libraryDependencies ++= Seq(
put this back in AppDependencies.scala file

2022-08-24 09:54 UTC, frikit commented on project/AppDependencies.scala
> +    "uk.gov.hmrc" %% "bootstrap-backend-play-28" % "7.0.0"
please keep 6.4 for now as there are some breaking changes in 7.0 that we are not aware of

2022-08-24 09:54 UTC, frikit commented on project/AppDependencies.scala
> +    "org.pegdown" % "pegdown" % "1.6.0",
I dont think we need this one as it is using flexmark but it is worth a try to remove

2022-08-24 09:54 UTC, frikit commented on project/plugins.sbt
scalafmt plugin missing along with conf file we discussed that we will add that as part of sbt updates

2022-08-24 09:54 UTC, frikit commented on build.sbt
optimize imports here

2022-08-31 13:07 UTC, Nboaram commented on project/AppDependencies.scala
> +    "org.pegdown" % "pegdown" % "1.6.0",
Tried, it threw a bunch of errors

2022-09-06 13:44 UTC, frikit commented on project/AppDependencies.scala
> +    "org.pegdown" % "pegdown" % "1.6.0",
You are not able to remove it because it didnt update all other deps like scalatest because some of them require this but not on latest versions, please make this change and push without pegdown

2022-09-08 09:44 UTC, frikit approved these changes

2022-09-08 10:01 UTC, merged